package:
  name: mms
  version: '0.0.3'

source:
  #git_url: git@github.com:ggnatalia/MMs.git
  git_url: https://github.com/ggnatalia/MMs
  #git_tag: dev
  #git_url: /home/natalia/opt/MMs/
  #md5: 

requirements:
  build:
    - python=3.7
    #- {{ compiler('python_c') }}
    - cython
    - numpy  
  run:
    - python=3.7  
      #- argparse 
      #- os
      #- sys
      #- shutil
    - numpy
    - scipy  
      #- math
    - pandas
    - scikit-learn
      #- random
      #- re
      #- glob
      #- logging
    - daiquiri
      #- collections
      #- itertools
      #- multiprocessing  
    - matplotlib
      #- seaborn  
    - mothur=1.44
    - biopython
    - joblib
    - pysam=0.15
    - requests
    - plotly
    - cython=0.29.21
    - htseq
    - pybedtools
    #- six

build:
  noarch: generic
test:
  imports:
    - numpy
    - pandas
    - scipy
    #- sklearn
    - daiquiri
    - pysam
    - plotly
  command: "pwd"

about:
  home:  https://github.com/ggnatalia/MMs
  license: GPL-3
  license_file: ../LICENSE
  summary: 'M&Ms: a software to generate Metagenomic samples from realistic microbial communities'
  description:
          "MMs is a automatic pipeline for generating metagenomic samples from realistic microbial communities
          \n
          \n
          To install this package with conda run:
          \n
          \n
          `conda create -n MMs -c auto -c anaconda -c bioconda -c conda-forge -c ggnatalia mms`
          \n
          \n
          And activate it with:
          \n
          \n
          `conda activate MMs`
          \n
          \n
          Detailed usage instructions can be found at <https://github.com/ggnatalia/MMs>"
  dev_url: https://github.com/ggnatalia/MMs
  doc_url: https://github.com/ggnatalia/MMs
  doc_source_url: https://github.com/ggnatalia/MMs/README.md
  recipe-maintainers:
      - ggnatalia
